copy method param._type.check

diff --git a/assert b/assert
--- a/assert
+++ b/assert
@@ -39,6 +39,116 @@ assert.selftest(){
 # when to use name evaluation?
 # 
 
+param._type.check(){
+    # shellcheck disable=SC2016
+    local CHOICE_LIST_MUST_NOT_BE_EMTPY='
+        [ "${#@}" -eq 0 ] && {
+            echo "ERROR: Please provide candidate list right after $op for parameter[$name]" >&2
+            param.help.show
+            return 0
+        }
+    '
+
+    local IFS=$'\n'
+
+    local name="$1" val="$2" op="$3"; shift 3
+    case "$op" in
+    =~)
+        eval "$CHOICE_LIST_MUST_NOT_BE_EMTPY"
+        if ! assert.within_regex "$val" "$@"; then
+            echo "ERROR:  $name='$val' NOT match any regex defined" >&2
+            param.help.show
+            return 1
+        fi;;
+    =)
+        eval "$CHOICE_LIST_MUST_NOT_BE_EMTPY"
+        if ! assert.within "$val" "$@"; then
+            # echo "$val" "$@" >&2
+            echo "ERROR: $name='$val' Not one of the candidate set." >&2
+            param.help.show
+            return 1
+        fi ;;
+    =str | =int)
+        if [ -z "${val}" ]; then
+            echo "ERROR: A non-null value is expected for parameter: $name" >&2
+            param.help.show
+            return 1
+        fi
+
+        if [ "$op" = "=int" ]; then
+            if  [[ ! "$val" =~ ^[\ \t]*[0-9]+[\ \t]*$ ]]; then
+                echo "ERROR: $name='$val' An integer expected." >&2
+                param.help.show
+                return 1
+            fi
+        fi
+
+        [ "${#@}" -ne 0 ] && {
+            if ! assert.within "$val" "$@"; then
+                echo "ERROR: $name='$val' Not inside the $op set." >&2
+                param.help.show
+                return 1
+            fi 
+        };;
+    =\[?\] | =?)
+        eval "$CHOICE_LIST_MUST_NOT_BE_EMTPY"
+
+        local sep=${op:1:1};
+        [[ "$op" == '=['?']' ]] &&  sep=${op:2:1}
+        # shellcheck disable=SC2207
+        local data=( $(echo "$val" | tr "$sep" '\n') ) # should not quote '$(...)'
+        [ ${#data[@]} -eq 0 ] && data=("")
+
+        local datum
+        for datum in "${data[@]}"; do
+            if ! assert.within "$datum" "$@"; then
+                echo "ERROR: [$name='$val'] After splited with \'$sep\', element '$datum' does NOT match the string set" >&2
+                param.help.show
+                return 1
+            fi
+        done
+
+        if [[ "$op" == '=['?']' ]]; then
+            [[ ! "$name" == \\\$* ]] && {
+                echo "local $name 2>/dev/null"
+                echo "$name=$(list.repr "${data[@]}")"
+            }
+            return 0 # continue
+        fi ;;
+    =~\[?\] | =~? )
+        eval "$CHOICE_LIST_MUST_NOT_BE_EMTPY"
+
+        local sep=${op:2:1};    
+        [[ "$op" == '=~['?']' ]] && sep=${op:3:1}
+        # shellcheck disable=SC2207
+        local data=( $(echo "$val" | tr "$sep" '\n') ) # should not quote '$(...)'
+        [ ${#data[@]} -eq 0 ] && data=("")
+
+        local datum
+        for datum in "${data[@]}"; do
+            assert.within_regex "$datum" "$@" && continue
+            echo "ERROR: [$name='$val']. After splited with \'$sep\', element '$datum' does NOT match the regex set." >&2
+            param.help.show
+            return 1
+        done
+
+        if [[ "$op" == '=~['?']' ]]; then
+            [[ ! "$name" == \\\$* ]] && {
+                echo "local $name 2>/dev/null"
+                echo "$name=$(list.repr "${data[@]}")"
+            }
+            return 0 # continue
+        fi ;;
+    *)  [ "$op" == "" ] || echo ": TODO: $op" >&2 ;;
+    esac
+
+    [[ ! "$name" == \\\$* ]] && {
+        echo "local $name 2>/dev/null"
+        echo "$name=$(str.repr "$val")"
+    }
+    return 0
+}
+
 assert(){
     local value="$1"
     local op="$2"
