modify cache module

diff --git a/cache b/cache
--- a/cache
+++ b/cache
@@ -14,6 +14,47 @@ str.md5(){
     fi
 }
 
+# TODO: Optimize this function.
+file.rmrf.safe(){
+    local i sw=0 filepath pattern pattern_list=() path_list=() hyphen2=0
+
+    for i in "$@"; do
+        if [ "$i" == -- ]; then
+            hyphen2=1
+        fi
+        if [ $hyphen2 -eq 0 ]; then
+            pattern_list+=("$i")
+        else
+            path_list+=("$i")
+        fi
+    done
+
+    if [ $hyphen2 -eq 0 ]; then
+        path_list=("${pattern_list[@]}")
+        pattern_list=()
+    fi
+
+    for filepath in "${path_list[@]}"; do
+        case "$filepath" in
+            /)      sw=1; printf "Detect rm -rf /" >&2      ;;
+            /bin*)  sw=1; printf "Detect rm -rf /bin" >&2   ;;
+            /home)  sw=1; printf "Detect rm -rf /home" >&2  ;;
+            *)      sw=1;
+                    for pattern in "${pattern_list[@]}"; do
+                        [[ "$filepath" =~ $pattern ]]
+                        printf "Detect violation of RULES: %s" "$pattern" >&2
+                    done;;
+        esac
+    done
+
+    if [ "$sw" -eq 1 ]; then
+        printf "file.rm.safe cannot remove the critical files. If you insists, please directly using rm command." >&2
+        return 1
+    fi
+
+    rm -rf "$@"
+}
+
 cache.debug(){
     local IFS=
     [[ "$X_BASH_DEUBG" =~ (^|,)(std/)*cache($|,) ]] && printf "DBG: %s\n" "$@" >&2
@@ -88,10 +129,12 @@ cache.cmd(){
         cat "$filepath"
     else
         [[ "$STD_DEBUG" == *cache* ]] && echo "FILEPATH does't exists or older than ${expiration} second. Update" >&2
-        
-        local temp_filepath; temp_filepath=$(mktemp)
-        { eval "$@" && rm "$filepath" 2>/dev/null; } | tee "$temp_filepath"
-        [ ! -f "$filepath" ] && mv "$temp_filepath" "$filepath"
+
+        local BACKUP_PATH="$filepath.x-bash.origin.ed15841d4fba5c1dba9045bcbfa0819a"
+        if mv "$filepath" "$BACKUP_PATH"; then
+            eval "$@" | tee "$filepath"
+            rm -rf "$BACKUP_PATH"
+        fi
     fi
 }
 
@@ -109,13 +152,6 @@ cache.cmd.setup(){
 
 # Remember teardown if you have setup
 cache.cmd.teardown(){
-    case "$X_CMD_X_BASH_CACHE_CMD_FOLDER" in
-        /);;
-        /bin*);;
-        /home*);;
-        # Do more work to protect the critical facility.
-        *) rm -rf "$X_CMD_X_BASH_CACHE_CMD_FOLDER"
-    esac
-
+    file.rmrf.safe "$X_CMD_X_BASH_CACHE_CMD_FOLDER"
     unset X_CMD_X_BASH_CACHE_CMD_FOLDER
 }
