param bugfix. now support multiple value

diff --git a/param b/param
--- a/param
+++ b/param
@@ -73,7 +73,7 @@ param.__parse(){
         IFS=$'\n'
 
         case "${all_arg_arr[1]}" in
-        = | =~ | :str | :str? | :float | :int | =[?] | =? | =~[?] | =~? )
+        = | =~ | :str | :str? | :float | :int | =\[?\] | =? | =~\[?\] | =~? )
             oplist+=( "${all_arg_arr[1]}" )
             choicelist+=( "${all_arg_arr[*]:2}" )
             ;;
@@ -82,9 +82,7 @@ param.__parse(){
             oplist+=( "${all_arg_arr[2]}" )
             choicelist+=( "${all_arg_arr[*]:3}" )
             ;;
-        esac
-
-        
+        esac 
 
         deslist+=("$description")
         typelist+=("argenv")
@@ -164,7 +162,7 @@ param.__parse(){
         =~)
             local match=0 c
             for c in "${choice[@]}"; do
-                if [[ "$val" =~ $c ]]; then
+                if [[ "$val" =~ ^($c)$ ]]; then
                     match=1
                     break
                 fi
@@ -219,10 +217,11 @@ param.__parse(){
                 echo 'return 1 2>/dev/null'
                 return 0
             fi ;;
-        =[?] | =?)
-            local sep=${op[1]} match
-            [[ "$op" == =[?] ]] &&  sep=${op[2]}
-            local data=("$(echo "$val" | tr "$sep" '\n')")
+        =\[?\] | =?)
+            local sep=${op:1:1} match
+            [[ "$op" == =\[?\] ]] &&  sep=${op:2:1}
+            local data=( $(echo "$val" | tr "$sep" '\n') )
+            [ ${#data[@]} -eq 0 ] && data=("")
             local datum
             for datum in "${data[@]}"; do
                 match=0
@@ -239,32 +238,34 @@ param.__parse(){
                 fi
             done
 
-            if [[ "$op" == =[?] ]]; then
+            if [[ "$op" == =\[?\] ]]; then
                 echo "local $name 2>/dev/null"
                 echo "$name=$(list.repr "${data[@]}")"
                 continue
             fi ;;
-        =~[?] | =~? )
-            local sep=${op[2]} i match
-            [[ "$op" == =~[?] ]] && sep=${op[3]}
-            local data=("$(echo "$val" | tr "$sep" '\n')")
+
+        =~\[?\] | =~? )
+            local sep=${op:2:1} i match
+            [[ "$op" == =~\[?\] ]] && sep=${op:3:1}
+            local data=( $(echo "$val" | tr "$sep" '\n') )
+            [ ${#data[@]} -eq 0 ] && data=("")
             local datum
             for datum in "${data[@]}"; do
                 match=0
                 for c in "${choice[@]}"; do
-                    if [[ "$datum" =~ $c ]]; then
+                    if [[ "$datum" =~ ^($c)$ ]]; then
                         match=1
                         break
                     fi
                 done
                 if [ $match -eq 0 ]; then
-                    echo "echo ERROR: $name='$val' Split with $sep and found one of the element is match the regex set >&2"
+                    echo "echo ERROR: $name='$val' Split with $sep and found none of the element is match the regex set >&2"
                     echo 'return 2 2>/dev/null'
                     return 0
                 fi
             done
 
-            if [[ "$op" == =[?] ]]; then
+            if [[ "$op" == =~\[?\] ]]; then
                 echo "local $name 2>/dev/null"
                 echo "$name=$(list.repr "${data[@]}")"
                 continue
