add path.rmrf.safe

diff --git a/path b/path
--- a/path
+++ b/path
@@ -112,3 +112,44 @@ path.rmrf(){
         rm -rf "$i"
     done
 }
+
+# TODO: check this function
+path.rmrf.safe(){
+    local i sw=0 filepath pattern pattern_list=() path_list=() hyphen2=0
+
+    for i in "$@"; do
+        if [ "$i" == -- ]; then
+            hyphen2=1
+        fi
+        if [ $hyphen2 -eq 0 ]; then
+            pattern_list+=("$i")
+        else
+            path_list+=("$i")
+        fi
+    done
+
+    if [ $hyphen2 -eq 0 ]; then
+        path_list=("${pattern_list[@]}")
+        pattern_list=()
+    fi
+
+    for filepath in "${path_list[@]}"; do
+        case "$filepath" in
+            /)      sw=1; printf "Detect rm -rf /" >&2      ;;
+            /bin*)  sw=1; printf "Detect rm -rf /bin" >&2   ;;
+            /home)  sw=1; printf "Detect rm -rf /home" >&2  ;;
+            *)      for pattern in "${pattern_list[@]}"; do
+                        sw=1
+                        [[ "$filepath" =~ $pattern ]]
+                        printf "Detect violation of RULES: %s" "$pattern" >&2
+                    done;;
+        esac
+    done
+
+    if [ "$sw" -eq 1 ]; then
+        printf "file.rm.safe cannot remove the critical files. If you insists, please directly using rm command." >&2
+        return 1
+    fi
+
+    rm -rf "$@"
+}
